package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"
	"fmt"

	"github.com/shirloin/backend/graph"
	"github.com/shirloin/backend/graph/model"
)

// Room is the resolver for the room field.
func (r *groupRoomUserResolver) Room(ctx context.Context, obj *model.GroupRoomUser) (*model.GroupRoom, error) {
	panic(fmt.Errorf("not implemented: Room - room"))
}

// User is the resolver for the user field.
func (r *groupRoomUserResolver) User(ctx context.Context, obj *model.GroupRoomUser) (*model.User, error) {
	panic(fmt.Errorf("not implemented: User - user"))
}

// GroupRoomUser returns graph.GroupRoomUserResolver implementation.
func (r *Resolver) GroupRoomUser() graph.GroupRoomUserResolver { return &groupRoomUserResolver{r} }

type groupRoomUserResolver struct{ *Resolver }
